require('dotenv').config(); // Loads the secrets from your .env file
const express = require('express');
const path = require('path');
const { OAuth2Client } = require('google-auth-library');
const mongoose = require('mongoose');

const app = express();

const client = new OAuth2Client(process.env.GOOGLE_CLIENT_ID);

app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

// ---------------------------------------------------------
// 1. MONGODB CONNECTION
// ---------------------------------------------------------
mongoose.connect(process.env.MONGO_URI)
    .then(() => console.log('✅ Connected to MongoDB Cloud!'))
    .catch((err) => console.error('❌ MongoDB Connection Error:', err));

// ---------------------------------------------------------
// 2. MONGODB DATABASE SCHEMA (How a meal is structured)
// ---------------------------------------------------------
const mealSchema = new mongoose.Schema({
    userEmail: { type: String, required: true }, // Ties the meal to a specific user
    id: { type: Number, required: true },        // The ID generated by your frontend
    type: { type: String, required: true },      // "חלבון" or "פחמימה"
    name: { type: String, required: true },
    weight: { type: Number, required: true },
    date: { type: String, required: true }
});

const Meal = mongoose.model('Meal', mealSchema);

// ---------------------------------------------------------
// 3. GOOGLE LOGIN MIDDLEWARE
// ---------------------------------------------------------
async function verifyUser(req, res, next) {
    const authHeader = req.headers.authorization;
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
        return res.status(401).json({ error: 'No token provided' });
    }

    const token = authHeader.split(' ')[1];
    
    try {
        const ticket = await client.verifyIdToken({
            idToken: token,
            audience: process.env.GOOGLE_CLIENT_ID,
        });
        const payload = ticket.getPayload();
        req.userEmail = payload.email; 
        next(); 
    } catch (error) {
        return res.status(401).json({ error: 'Invalid or expired token' });
    }
}

// ---------------------------------------------------------
// 4. API ROUTES
// ---------------------------------------------------------

// GET: Fetch ALL meals for the logged-in user
app.get('/api/meals', verifyUser, async (req, res) => {
    try {
        // Find all meals in the DB where userEmail matches the logged-in user
        const userMeals = await Meal.find({ userEmail: req.userEmail });
        res.json(userMeals);
    } catch (error) {
        res.status(500).json({ error: 'Failed to fetch meals' });
    }
});

// POST: Save a new meal for the logged-in user
app.post('/api/meals', verifyUser, async (req, res) => {
    try {
        // Create a new meal document, attaching the user's email to it
        const newMeal = new Meal({
            userEmail: req.userEmail,
            id: req.body.id,
            type: req.body.type,
            name: req.body.name,
            weight: req.body.weight,
            date: req.body.date
        });
        
        // Save it to MongoDB
        await newMeal.save();
        res.status(201).json({ message: 'Meal saved successfully' });
    } catch (error) {
        res.status(500).json({ error: 'Failed to save meal' });
    }
});

// DELETE: Remove a meal by ID (only if it belongs to the user)
app.delete('/api/meals/:id', verifyUser, async (req, res) => {
    try {
        await Meal.findOneAndDelete({ 
            id: parseInt(req.params.id), 
            userEmail: req.userEmail // Extra security: ensure they own the meal
        });
        res.json({ message: 'Meal deleted' });
    } catch (error) {
        res.status(500).json({ error: 'Failed to delete meal' });
    }
});

// ---------------------------------------------------------
// 5. START SERVER
// ---------------------------------------------------------

// Export the Express API for Vercel's serverless environment
module.exports = app;